## About Dataset
Context
This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content
5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.
Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.

Acknowledgements
This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration
- Sentiment analysis on reviews.
- Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
- Fake reviews/ outliers.
- Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
- Any other interesting analysis

#### Best Practises
1. Preprocessing And Cleaning
2. Train Test Split
3. BOW,TFIDF,Word2vec
4. Train ML algorithms

In [1]:
# Load the dataset
# import pandas as pd
# data=pd.read_csv('Kindle Reviews/all_kindle_review.csv')
# data.head()

In [2]:
# df=data[['reviewText','rating']]
# df.head()

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

os.listdir('/content/drive/MyDrive')

['Getting started.pdf',
 'user_agreement_Abhishek Upadhayay_+917250652389.pdf',
 'Sharer.pw',
 'Scan Jan 9, 2019 (5).pdf',
 'Scan Jan 9, 2019.pdf',
 'Download',
 'Batch_Dec_Complete_Ds_ML',
 'Batch_April',
 'can you provide a detailed excel file with all fo....gsheet',
 'Functions and Formulas.gdoc',
 'Some new youn can do.gdoc',
 'Audio',
 'Batch_Sept',
 'DDS 07',
 'DDS 02',
 'CX_DS_B01',
 'CX_DA_C01',
 'b_02',
 'Downloads new2026',
 'CognitiaXAI-LMS',
 'syllabus',
 'System',
 'Videos imp',
 'Voting_Classifiers.pptx',
 'Colab Notebooks',
 'NLP',
 'Vedic astrology expert AI with deep knowledge of kundli analysis.gdoc',
 'Untitled document.gdoc',
 'genai_career_roadmap.html',
 'remote-jobs-guide.html',
 'ml_dl_visualization_guide_1.html',
 'How_to_Create_a_Claude_Skill.pdf',
 'SKC_Projects',
 'Transformations_Kartik',
 'Sample Tableau Resumes',
 'UPDATED AI Placement Sprint Roadmap.gsheet',
 'Weekend',
 'TABLEAU EXERCISES_1',
 'Tableau',
 'data_interview',
 'NLP_10_12_Weekend',
 'sms_spam_ham',
 'Copy of earn_with_ai_guide.pdf',
 'Setup Instructions For Less Claude Tokens.gdoc',
 'Claude Design: Your Quick Start Guide.gdoc',
 'Copy of Day2Notes.pdf',
 'Google_Photos_Main_account_All',
 'Seedance 2 airport.gdoc',
 'Edoxi_Data_analysis',
 'SHAred in main',
 'Kindle Reviews',
 'SpamClassifier-master',
 'Youtube',
 'Set_YouTube.gdoc',
 'books']

In [4]:
import pandas as pd

file_path = '/content/drive/MyDrive/Kindle Reviews/all_kindle_review.csv'
df = pd.read_csv(file_path)

df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [8]:
data = df[['reviewText', 'rating']]
data.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [9]:
data.shape

(12000, 2)

In [10]:
## Missing Values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [11]:
data['rating'].unique()

array([3, 5, 4, 2, 1])

In [12]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [ ]:
## Preprocessing And Cleaning

In [13]:
## postive review is 1 and negative review is 0
data['rating']=data['rating'].apply(lambda x:0 if x<3 else 1)

In [ ]:
df['rating'].value_counts()

1    8000
0    4000
Name: rating, dtype: int64

In [14]:
## 1. Lower All the cases
data['reviewText']=data['reviewText'].str.lower()

In [15]:
data.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [16]:
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [17]:
from bs4 import BeautifulSoup

In [ ]:
# The goal is to make messy review text clean, consistent, and useful for machine learning or sentiment analysis.

In [18]:
## Removing special characters
# Special characters usually do not help in understanding meaning of text for NLP models.
data['reviewText']=data['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
data['reviewText']=data['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
data['reviewText']=data['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
data['reviewText']=data['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
data['reviewText']=data['reviewText'].apply(lambda x: " ".join(x.split()))

In [19]:
data.head()

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1

In [24]:
## Lemmatizer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [25]:
lemmatizer=WordNetLemmatizer()

In [26]:
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [27]:
data['reviewText']=data['reviewText'].apply(lambda x:lemmatize_words(x))

In [28]:
data.head()

                                          reviewText  rating
0  jace rankin may short he nothing mess man haul...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four book wasnt expecti...       1
3  aggie angela lansbury carry pocketbook instead...       1
4  expect type book library pleased find price right       1

In [29]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data['reviewText'],data['rating'],
                                              test_size=0.20)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()
X_train_bow=bow.fit_transform(X_train).toarray()
X_test_bow=bow.transform(X_test).toarray()

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
X_train_tfidf=tfidf.fit_transform(X_train).toarray()
X_test_tfidf=tfidf.transform(X_test).toarray()

In [32]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
from sklearn.naive_bayes import GaussianNB
nb_model_bow=GaussianNB().fit(X_train_bow,y_train)
nb_model_tfidf=GaussianNB().fit(X_train_tfidf,y_train)

In [34]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [35]:
y_pred_bow=nb_model_bow.predict(X_test_bow)

In [36]:
y_pred_tfidf=nb_model_bow.predict(X_test_tfidf)

In [37]:
confusion_matrix(y_test,y_pred_bow)

array([[514, 265],
       [737, 884]])

In [38]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.5825

In [39]:
confusion_matrix(y_test,y_pred_tfidf)

array([[506, 273],
       [727, 894]])

In [40]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.5833333333333334